export const NAVIGATION_NAVIGATE = 'NAVIGATION_NAVIGATE';
export const NAVIGATION_INIT = 'NAVIGATION_INIT';

export const USER_DATA_SET = 'USER_DATA_SET';
export const USER_DATA_UPDATE = 'USER_DATA_UPDATE';

export const SET_EDITING_INFO = 'SET_EDITING_INFO';
